#title: Assignment 2 (02806) - Investigation of Correlation Between Narcotic and Assault Incidents in San Francisco
description: In this analysis of San Francisco Crime Data, we've uncovered trends in narcotic and assault-related incidents across the city. The analysis reveals shifts in the number of incidents within both crime types. Furthermore, we investigate the correlation between these crime types across different areas of the city.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman