#title: Assignment 2 (02806) - Investigation of Correlation Between Narcotic and Assault Incidents in San Francisco
description: Our analysis highlights the rapid growth of the global electric vehicle (EV) market, driven by environmental concerns, innovation, and government support.  Using Palo Alto as a case study, we demonstrate how understanding charging patterns can optimize EV infrastructure, and we identify broader economic and social factors that influence the success of EVs worldwide.
#show_downloads: false
google_analytics:
theme: jekyll-theme-cayman